### ISSUE TITLE
JSON Errors

### ISSUE THREAD

**Issue by littleidiot40** [nasa-esdswg-ml/edc-notebooks#1]
For training.ipynb cell 4. I can't find anything wrong with the JSON input or the Augmented Manifest files (the ones that refer to the doug buckets)
Training failed to start
Training failed with the following error: ClientError: Invalid JSON string found. Please ensure data is in the expected JSON formats
, exit code: 2

**Comment by littleidiot40** [comment]
@jinbow not technically assigned to you but if you could take a look at my code... :)

**Comment by jinbow** [comment]
I will not be helpful on this one, Doug. But a quick reflex: does the error persist if you plan the json files in your local folder?

**Comment by littleidiot40** [comment]
I figured it out. It was not invalid JSON. It was a validation augmented manifest file without classifications. Doh. Poor error!
